### ISSUE TITLE
Error while using conc from Command line in Windows

### ISSUE THREAD

**Issue by vsrohit** [Concurnas/Concurnas#25]
I have installed Concurnas using the Microsoft installer provided in the Website version 1.14.019. The installation was successful. I have added the required path variable.

I am getting the following error:
```
Caching runtime enviroment for Concurnas version: 1.14.019 and JVM Spec: 11.0.2. This needs to be done only once. This may take a few minutes...
Error in cache genneration: Illegal character in opaque part at index 20: jar:file:/C:/Program Files/Concurnas/rtCache/tdrzkhqu/java.base.jar
java.lang.IllegalArgumentException: Illegal character in opaque part at index 20: jar:file:/C:/Program Files/Concurnas/rtCache/tdrzkhqu/java.base.jar
        at java.base/java.net.URI.create(URI.java:883)
        at com.concurnas.runtimeCache.StaticLambdaClassesFinder.buildGraphAndGetDirectStaticLambdas(StaticLambdaClassesFinder.java:59)
        at com.concurnas.runtimeCache.StaticLambdaClassesFinder.go(StaticLambdaClassesFinder.java:113)
        at com.concurnas.runtimeCache.RuntimeCacheModules.doAug(RuntimeCacheModules.java:142)
        at com.concurnas.runtimeCache.RuntimeCache.doAgumentation(RuntimeCache.java:56)
        at com.concurnas.runtimeCache.RuntimeCacheCreator.makeCache(RuntimeCacheCreator.java:19)
        at com.concurnas.conc.ConcWrapper.performCache(ConcWrapper.java:125)
        at com.concurnas.conc.ConcWrapper.access$100(ConcWrapper.java:26)
        at com.concurnas.conc.ConcWrapper$CacheEstablisher.establishCache(ConcWrapper.java:229)
        at com.concurnas.conc.ConcWrapper$CacheEstablisher.access$500(ConcWrapper.java:137)
        at com.concurnas.conc.ConcWrapper.main(ConcWrapper.java:300)
Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 20: jar:file:/C:/Program Files/Concurnas/rtCache/tdrzkhqu/java.base.jar
        at java.base/java.net.URI$Parser.fail(URI.java:2915)
        at java.base/java.net.URI$Parser.checkChars(URI.java:3086)
        at java.base/java.net.URI$Parser.parse(URI.java:3122)
        at java.base/java.net.URI.<init>(URI.java:600)
        at java.base/java.net.URI.create(URI.java:881)
        ... 10 more
``

**Comment by vsrohit** [comment]
I have run the 'conc' command from git bash. But running it from command prompt worked. After the cache was built I could use the REPL.
