### ISSUE TITLE
Running a series of GPU examples in REPL causes OOM

### ISSUE THREAD

**Issue by denkab** [Concurnas/Concurnas#53]
1. JDK used: Graal VM / OpenJDK 11.0.7 on Windows 10
2. starting `conc -J-Xmx2g`

...>conc -J-Xmx2g
[Use -Dgraal.LogFile=<path> to redirect Graal log output to a file.]
Cannot install GraalVM MBean due to Cannot find method registerNativeMethods due to java.lang.InternalError:java.lang.IllegalAccessException: class com.concurnas.bootstrap.runtime.cps.ReflectionHelper (in module java.base) cannot access class jdk.vm.ci.hotspot.HotSpotJVMCIRuntime (in module jdk.internal.vm.ci) because module jdk.internal.vm.ci does not export jdk.vm.ci.hotspot to module java.base.
Welcome to Concurnas 1.14.020 (OpenJDK 64-Bit Server VM, Java 11.0.7).

3. Running GPU examples from https://concurnas.com/docs/gpuParallelProgramming.html
4. After executing 
```
gps = gpus.GPU()
deviceGrp = gps.getGPUDevices()[0]
summary = deviceGrp getSummary()
device = deviceGrp.devices[0]
inoutGPU = device.makeOffHeapArrayMixed<int[]>(int[].class, 10)
copyComplete boolean:gpus.GPURef = inoutGPU.writeToBuffer([1 2 3 4 5 6 7 8 9 10])
await(copyComplete)
```

observe runaway heap consumption in VisualVM, which ends up with exception trace

java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.HashMap.resize(HashMap.java:699)
        at java.base/java.util.HashMap.putVal(HashMap.java:624)
        at java.base/java.util.HashMap.put(HashMap.java:607)
        at org.antlr.v4.runtime.atn.PredictionContext.combineCommonParents(PredictionContext.java:476)
        at org.antlr.v4.runtime.atn.PredictionContext.mergeArrays(PredictionContext.java:459)
        at org.antlr.v4.runtime.atn.PredictionContext.merge(PredictionContext.java:174)
        at org.antlr.v4.runtime.atn.PredictionContext.mergeSingletons(PredictionContext.java:225)
        at org.antlr.v4.runtime.atn.PredictionContext.merge(PredictionContext.java:155)
        at org.antlr.v4.runtime.atn.PredictionContext.mergeSingletons(PredictionContext.java:225)
        at org.antlr.v4.runtime.atn.PredictionContext.merge(PredictionContext.java:155)
        ...

and after a while, REPL terminates as well due to OOM

**Comment by jasontatton** [comment]
Thanks for raising this, I will have a look into this
