### ISSUE TITLE
Some filenames cause compilation to fail

### ISSUE THREAD

**Issue by kliberty** [Concurnas/Concurnas#70]
`concc` cannot build files named `c.conc`. `conc.conc` also fails, but `cc.conc` compiles successfully. This was tested with version `1.14.020`.

```
Unable to compile as Unable to find source (.conc) or compiled (.class) code associated with: /tmp/c.co/c. Neither: /tmp/c.co.class or /tmp/c.co/c.conc exist
java.lang.Exception: Unable to find source (.conc) or compiled (.class) code associated with: /tmp/c.co/c. Neither: /tmp/c.co.class or /tmp/c.co/c.conc exist
        at com.concurnas.compiler.ModuleCompiler.checkSourceExists(ModuleCompiler.java:145)
        at com.concurnas.compiler.ModuleCompiler.<init>(ModuleCompiler.java:113)
        at com.concurnas.compiler.MainLoop.getModuleCompilerForFile(MainLoop.java:629)
        at com.concurnas.compiler.MainLoop.compileFile(MainLoop.java:313)
        at com.concurnas.concc.Concc.doMain(Concc.java:228)
        at com.concurnas.concc.Concc.doit(Concc.java:145)
        at com.concurnas.concc.Concc.main(Concc.java:89)
Unable to compile as Unable to find source (.conc) or compiled (.class) code associated with: /tmp/./c.co/c. Neither: /tmp/c.co.class or /tmp/c.co/c.conc exist
java.lang.Exception: Unable to find source (.conc) or compiled (.class) code associated with: /tmp/./c.co/c. Neither: /tmp/c.co.class or /tmp/c.co/c.conc exist
        at com.concurnas.compiler.ModuleCompiler.checkSourceExists(ModuleCompiler.java:145)
        at com.concurnas.compiler.ModuleCompiler.<init>(ModuleCompiler.java:113)
        at com.concurnas.compiler.MainLoop.getModuleCompilerForFile(MainLoop.java:629)
        at com.concurnas.compiler.MainLoop.compileFile(MainLoop.java:313)
        at com.concurnas.concc.Concc.doMain(Concc.java:228)
        at com.concurnas.concc.Concc.doit(Concc.java:145)
        at com.concurnas.concc.Concc.main(Concc.java:89)
Unable to compile as null
java.lang.NullPointerException
        at com.concurnas.compiler.MainLoop.compileFile(MainLoop.java:356)
        at com.concurnas.concc.Concc.doMain(Concc.java:228)
        at com.concurnas.concc.Concc.doit(Concc.java:145)
        at com.concurnas.concc.Concc.main(Concc.java:89)
/tmp/c.conc[ true] line 0:0 Unable to compile as Unable to find source (.conc) or compiled (.class) code associated with: /tmp/c.co/c. Neither: /tmp/c.co.class or /tmp/c.co/c.conc exist
/tmp/./c.conc[ false] line 0:0 Unable to compile as Unable to find source (.conc) or compiled (.class) code associated with: /tmp/./c.co/c. Neither: /tmp/c.co.class or /tmp/c.co/c.conc exist
/tmp/c.conc[ true] line 0:0 Unable to compile as null
```

**Comment by jasontatton** [comment]
Thanks for raising this. That's an interesting problem
